/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CabekaDAO;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Cabeka;

/**
 *
 * @author rifqi
 */
public class CabekaView extends javax.swing.JFrame {
    private ArrayList<JTextField> textFields;
    CabekaDAO dao = new CabekaDAO();
    Cabeka cabeka;
    /**
     * Creates new form CabekaView
     */
    public CabekaView() {
        initComponents();
        textFields = new ArrayList<>();
        textFields.add(inputInduk);
        textFields.add(inputGuru);
        textFields.add(inputPermasalahan);
        textFields.add(inputSolusi);
        textFields.add(tfNamaSiswa);
        textFields.add(tfNamaGuru);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        header_text = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputInduk = new javax.swing.JTextField();
        btnLookupSiswa = new javax.swing.JButton();
        tfNamaSiswa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tgl = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        inputGuru = new javax.swing.JTextField();
        btnLookupGuru = new javax.swing.JButton();
        tfNamaGuru = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputPermasalahan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputSolusi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboKehadiran = new javax.swing.JComboBox<>();
        scrCabeka = new javax.swing.JScrollPane();
        tblCabeka = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(0, 0, 153));

        header_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        header_text.setForeground(new java.awt.Color(255, 255, 255));
        header_text.setText("DATA CABEKA");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(header_text)
                .addContainerGap(818, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_text, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nomor Induk");

        inputInduk.setOpaque(true);
        inputInduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIndukActionPerformed(evt);
            }
        });
        inputInduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputIndukKeyReleased(evt);
            }
        });

        btnLookupSiswa.setText("Lookup");
        btnLookupSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupSiswaActionPerformed(evt);
            }
        });

        tfNamaSiswa.setEditable(false);
        tfNamaSiswa.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal");

        Tgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TglPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("GuruPengampu");

        inputGuru.setOpaque(true);
        inputGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGuruActionPerformed(evt);
            }
        });
        inputGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputGuruKeyReleased(evt);
            }
        });

        btnLookupGuru.setText("Lookup");
        btnLookupGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupGuruActionPerformed(evt);
            }
        });

        tfNamaGuru.setEditable(false);
        tfNamaGuru.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Permasalahan");

        inputPermasalahan.setOpaque(true);
        inputPermasalahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPermasalahanActionPerformed(evt);
            }
        });
        inputPermasalahan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputPermasalahanKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Solusi");

        inputSolusi.setOpaque(true);
        inputSolusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSolusiActionPerformed(evt);
            }
        });
        inputSolusi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSolusiKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Kehadiran");

        comboKehadiran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Sakit", "Izin", "Alpha" }));
        comboKehadiran.setSelectedIndex(-1);
        comboKehadiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKehadiranActionPerformed(evt);
            }
        });

        tblCabeka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCabeka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCabekaMousePressed(evt);
            }
        });
        scrCabeka.setViewportView(tblCabeka);

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(inputPermasalahan, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSolusi, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(656, 656, 656)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrCabeka)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(757, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inputPermasalahan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputSolusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(deleteBtn)
                    .addComponent(clearBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrCabeka, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLookupGuru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNamaGuru))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputInduk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLookupSiswa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputInduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupSiswa)
                    .addComponent(tfNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupGuru)
                    .addComponent(tfNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputIndukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIndukKeyReleased
        tfNamaSiswa.setText(dao.getNamaSiswa(inputInduk.getText()));                                  
        loadData();
    }//GEN-LAST:event_inputIndukKeyReleased

    private void btnLookupSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupSiswaActionPerformed
        LookView look = new LookView(this, true, "Data Siswa", dao.getLookSiswa(), "CabekaView");
        look.setVisible(true);
    }//GEN-LAST:event_btnLookupSiswaActionPerformed

    private void inputGuruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputGuruKeyReleased
        tfNamaGuru.setText(dao.getNamaGuru(inputGuru.getText()));                                  
        loadData();
    }//GEN-LAST:event_inputGuruKeyReleased

    private void btnLookupGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupGuruActionPerformed
        LookView look = new LookView(this, true, "Data Guru", dao.getLookGuru(), "CabekaView");
        look.setVisible(true);
    }//GEN-LAST:event_btnLookupGuruActionPerformed

    private void inputPermasalahanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPermasalahanKeyReleased
        loadData();
    }//GEN-LAST:event_inputPermasalahanKeyReleased

    private void inputSolusiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSolusiKeyReleased
        loadData();
    }//GEN-LAST:event_inputSolusiKeyReleased

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        loadData();
    }//GEN-LAST:event_formPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Tgl.setMaxSelectableDate(new java.util.Date());
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (checkFill() == false) {
            JOptionPane.showMessageDialog(this, "Anda belum menginput semuanya");
            return;
        }
        
        if (JOptionPane.showConfirmDialog(null, "Data akan disimpan. Lanjutkan?", "Konfirmasi Simpan Data", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }

        Cabeka cabeka = new Cabeka();
        cabeka.setNis(inputInduk.getText());
        cabeka.setPermasalahan(inputPermasalahan.getText());
        cabeka.setSolusi(inputSolusi.getText());
        cabeka.setKehadiran(comboKehadiran.getSelectedItem().toString());
        cabeka.setPetugasBK(inputGuru.getText());
        cabeka.setTgl(new java.sql.Date(Tgl.getDate().getTime()));

        dao.saveCabeka(cabeka);
        loadData();
        removeInput();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (confirm("Data akan dihapus", "Hapus Data") == JOptionPane.NO_OPTION) return;
        dao.deleteCabeka(inputInduk.getText(), new java.sql.Date(Tgl.getDate().getTime()));
        loadData();
        removeInput();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tblCabekaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCabekaMousePressed
        int selectedRow = tblCabeka.rowAtPoint(evt.getPoint());

        if (selectedRow != -1) {
            String nis = tblCabeka.getValueAt(selectedRow, 0).toString(); 
            String tanggal = tblCabeka.getValueAt(selectedRow, 2).toString(); 

            loadDataTF(new String[] {nis, "", tanggal});
        }
        loadData();
    }//GEN-LAST:event_tblCabekaMousePressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadData();
    }//GEN-LAST:event_formWindowGainedFocus

    private void comboKehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKehadiranActionPerformed
        loadData();
    }//GEN-LAST:event_comboKehadiranActionPerformed

    private void inputSolusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSolusiActionPerformed
        loadData();
    }//GEN-LAST:event_inputSolusiActionPerformed

    private void inputPermasalahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPermasalahanActionPerformed
        loadData();
    }//GEN-LAST:event_inputPermasalahanActionPerformed

    private void inputGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGuruActionPerformed
        loadData();
    }//GEN-LAST:event_inputGuruActionPerformed

    private void inputIndukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIndukActionPerformed
        loadData();
    }//GEN-LAST:event_inputIndukActionPerformed

    private void TglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TglPropertyChange
        loadData();
    }//GEN-LAST:event_TglPropertyChange

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        if (confirm("Input akan dihapus", "Hapus Input Data") == JOptionPane.NO_OPTION) return;
        removeInput();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CabekaView().setVisible(true);
            }
        });
    }
    
    private void loadData() {
         String tgl = "";
         if (Tgl.getDate() != null) {
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             tgl = sdf.format(Tgl.getDate());
         }

         String[] args = {
             inputInduk.getText(),
             tgl
         };

         tblCabeka.setModel(dao.getModelAllCabeka(args));
         scrCabeka.setViewportView(tblCabeka);
     }
    
    private void loadDataTF(String[] data) {
        if (data.length < 3) {
            System.out.println("Invalid data array length.");
            return;
        }

        Cabeka cabeka = new Cabeka();
        cabeka.setNis(data[0]);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date utilDate = sdf.parse(data[2]);

            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            cabeka.setTgl(sqlDate);

        } catch (ParseException e) {
            System.out.println("Date parsing error: " + e.getMessage());
            return;
        }

        this.cabeka = dao.getSingleCabeka(cabeka);

        if (this.cabeka == null) {
            System.out.println("Cabeka not found for NIS: " + data[0]);
            return;
        }

        inputInduk.setText(this.cabeka.getNis());
        inputPermasalahan.setText(this.cabeka.getPermasalahan());
        inputSolusi.setText(this.cabeka.getSolusi());
        inputGuru.setText(this.cabeka.getPetugasBK());
        comboKehadiran.setSelectedItem(this.cabeka.getKehadiran());
        Tgl.setDate(this.cabeka.getTgl());

        tfNamaSiswa.setText(this.cabeka.getSiswa().getNama());
        tfNamaGuru.setText(this.cabeka.getGuru().getNama());
    }

    private void removeInput() {
        for (JTextField textField : textFields) {
            textField.setText("");
        }

        if (comboKehadiran != null) {
            comboKehadiran.setSelectedItem(null); 
        }

        if (Tgl != null) {
            Tgl.setDate(null);
        }
    }
    
    public boolean checkFill() {
        for (JTextField textField : textFields) {
            if (textField.getText().isEmpty()) {
                return false;
            }
        }
        if (comboKehadiran.getSelectedItem() == null) {
            return false;
        }
        if (Tgl.getDate() == null) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tgl;
    private javax.swing.JButton btnLookupGuru;
    private javax.swing.JButton btnLookupSiswa;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> comboKehadiran;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header_text;
    public static javax.swing.JTextField inputGuru;
    public static javax.swing.JTextField inputInduk;
    public static javax.swing.JTextField inputPermasalahan;
    public static javax.swing.JTextField inputSolusi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton saveBtn;
    private javax.swing.JScrollPane scrCabeka;
    private javax.swing.JTable tblCabeka;
    public static javax.swing.JTextField tfNamaGuru;
    public static javax.swing.JTextField tfNamaSiswa;
    // End of variables declaration//GEN-END:variables

    private int confirm(String text, String title) {
        return JOptionPane.showOptionDialog(null, text, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }

}

