package view;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Serge
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenkel = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUtility = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemChangePasssword = new javax.swing.JMenuItem();
        itemChangeUser = new javax.swing.JMenuItem();
        menuDataMaster = new javax.swing.JMenu();
        itemDataGuru = new javax.swing.JMenuItem();
        itemDataSiswa = new javax.swing.JMenuItem();
        ItemDataJurusai = new javax.swing.JMenuItem();
        itemDataMapel = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuRapot = new javax.swing.JMenu();
        itemRapotSiswa = new javax.swing.JMenuItem();
        menuAbsensi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuUtility.setText("Utility");

        itemLogout.setText("Logout");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        menuUtility.add(itemLogout);

        itemChangePasssword.setText("Change Password");
        menuUtility.add(itemChangePasssword);

        itemChangeUser.setText("Change User");
        menuUtility.add(itemChangeUser);

        jMenuBar1.add(menuUtility);

        menuDataMaster.setText("Data Master");

        itemDataGuru.setText("Data Guru");
        itemDataGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemDataGuruMousePressed(evt);
            }
        });
        menuDataMaster.add(itemDataGuru);

        itemDataSiswa.setText("Data Siswa");
        itemDataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemDataSiswaMousePressed(evt);
            }
        });
        menuDataMaster.add(itemDataSiswa);

        ItemDataJurusai.setText("Data Jurusan");
        ItemDataJurusai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ItemDataJurusaiMousePressed(evt);
            }
        });
        menuDataMaster.add(ItemDataJurusai);

        itemDataMapel.setText("Data Mata Pelajaran");
        itemDataMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemDataMapelMousePressed(evt);
            }
        });
        menuDataMaster.add(itemDataMapel);

        jMenuBar1.add(menuDataMaster);

        menuLaporan.setText("Laporan");

        menuRapot.setText("Rapot");

        itemRapotSiswa.setText("Rapot Siswa");
        itemRapotSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemRapotSiswaMousePressed(evt);
            }
        });
        menuRapot.add(itemRapotSiswa);

        menuLaporan.add(menuRapot);

        menuAbsensi.setText("Absensi");
        menuLaporan.add(menuAbsensi);

        jMenuBar1.add(menuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void itemDataSiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDataSiswaMousePressed
        // TODO add your handling code here:
        SiswaView siswa = new SiswaView();
        siswa.setVisible(true);
    }//GEN-LAST:event_itemDataSiswaMousePressed

    private void itemDataGuruMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDataGuruMousePressed
        // TODO add your handling code here:
        GuruView guru = new GuruView();
        guru.setVisible(true);
    }//GEN-LAST:event_itemDataGuruMousePressed

    private void ItemDataJurusaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemDataJurusaiMousePressed
        // TODO add your handling code here:
        JurusanView jurusan = new JurusanView();
        jurusan.setVisible(true);
    }//GEN-LAST:event_ItemDataJurusaiMousePressed

    private void itemDataMapelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDataMapelMousePressed
        // TODO add your handling code here:
        MataPelajaranView mapel = new MataPelajaranView();
        mapel.setVisible(true);
    }//GEN-LAST:event_itemDataMapelMousePressed

    private void itemRapotSiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRapotSiswaMousePressed
        NilaiView nilai = new NilaiView();
        nilai.setVisible(true);
    }//GEN-LAST:event_itemRapotSiswaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setVisible(true);
//                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemDataJurusai;
    private javax.swing.JMenuItem itemChangePasssword;
    private javax.swing.JMenuItem itemChangeUser;
    private javax.swing.JMenuItem itemDataGuru;
    private javax.swing.JMenuItem itemDataMapel;
    private javax.swing.JMenuItem itemDataSiswa;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemRapotSiswa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.ButtonGroup jenkel;
    private javax.swing.JMenu menuAbsensi;
    private javax.swing.JMenu menuDataMaster;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuRapot;
    private javax.swing.JMenu menuUtility;
    // End of variables declaration//GEN-END:variables
}
