/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import koneksi.Koneksi;
import dao.SiswaDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import model.Siswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Serge
 */
public class SiswaView extends javax.swing.JFrame {
    
    private ArrayList<JTextField> textFields;
    SiswaDAO dao;
    String nisSiswa;
    Siswa siswa;
    
    String namaFile;

    /**
     * Creates new form SiswaView
     */
    public SiswaView() {
        initComponents();
        dao = new SiswaDAO();
        textFields = new ArrayList<>();
        textFields.add(inputNis);
        textFields.add(inputNama);
        textFields.add(inputTelepon);
        textFields.add(inputAyah);
        textFields.add(inputIbu);
        textFields.add(inputTmpLahir);
        textFields.add(inputUser);
        nisSiswa = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupJenkel = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formInput = new javax.swing.JPanel();
        inputNis = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        telepon = new javax.swing.JLabel();
        jenkel = new javax.swing.JLabel();
        inputTelepon = new javax.swing.JTextField();
        inputRBLaki = new javax.swing.JRadioButton();
        inputRBPerempuan = new javax.swing.JRadioButton();
        inputAyah = new javax.swing.JTextField();
        tmplahir = new javax.swing.JLabel();
        ayah = new javax.swing.JLabel();
        inputTmpLahir = new javax.swing.JTextField();
        tgllahir = new javax.swing.JLabel();
        inputIbu = new javax.swing.JTextField();
        ibu = new javax.swing.JLabel();
        nis = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        inputTglLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        foto = new javax.swing.JLabel();
        inputFoto = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        interectPanel = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        scrSiswa = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Data Siswa");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        nama.setText("Nama");

        telepon.setText("Telepon");

        jenkel.setText("Jenis Kelamin");

        groupJenkel.add(inputRBLaki);
        inputRBLaki.setText("Laki-Laki");

        groupJenkel.add(inputRBPerempuan);
        inputRBPerempuan.setText("Perempuan");

        tmplahir.setText("Tempat Lahir");

        ayah.setText("Ayah Kandung");

        tgllahir.setText("Tanggal Lahir");

        ibu.setText("Ibu Kandung");

        nis.setText("NIS");

        alamat.setText("Alamat");

        user.setText("User");

        inputTglLahir.setDateFormatString("dd/MM/yyyy");

        inputAlamat.setColumns(20);
        inputAlamat.setLineWrap(true);
        inputAlamat.setRows(5);
        jScrollPane2.setViewportView(inputAlamat);

        foto.setText("Foto");

        inputFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUpload.setText("Upload Foto");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formInputLayout = new javax.swing.GroupLayout(formInput);
        formInput.setLayout(formInputLayout);
        formInputLayout.setHorizontalGroup(
            formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nis)
                    .addComponent(nama)
                    .addComponent(jenkel)
                    .addComponent(tmplahir)
                    .addComponent(tgllahir)
                    .addComponent(alamat))
                .addGap(43, 43, 43)
                .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(inputNis, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formInputLayout.createSequentialGroup()
                        .addComponent(inputRBLaki)
                        .addGap(37, 37, 37)
                        .addComponent(inputRBPerempuan))
                    .addComponent(inputNama)
                    .addComponent(inputTmpLahir)
                    .addComponent(inputTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(130, 130, 130)
                .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telepon)
                    .addComponent(ayah)
                    .addComponent(ibu)
                    .addComponent(user)
                    .addComponent(foto))
                .addGap(36, 36, 36)
                .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputIbu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputAyah)
                    .addComponent(inputTelepon)
                    .addComponent(inputUser)
                    .addGroup(formInputLayout.createSequentialGroup()
                        .addComponent(inputFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpload)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formInputLayout.setVerticalGroup(
            formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formInputLayout.createSequentialGroup()
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis)
                            .addComponent(inputNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenkel)
                            .addComponent(inputRBLaki)
                            .addComponent(inputRBPerempuan))
                        .addGap(18, 18, 18)
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tmplahir)
                            .addComponent(inputTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formInputLayout.createSequentialGroup()
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telepon))
                        .addGap(18, 18, 18)
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ayah))
                        .addGap(18, 18, 18)
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibu))
                        .addGap(13, 13, 13)
                        .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user)
                            .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(formInputLayout.createSequentialGroup()
                            .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tgllahir)
                                .addComponent(foto))
                            .addGap(18, 18, 18)
                            .addGroup(formInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alamat)
                                .addComponent(jScrollPane2)))
                        .addComponent(inputFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpload))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout interectPanelLayout = new javax.swing.GroupLayout(interectPanel);
        interectPanel.setLayout(interectPanelLayout);
        interectPanelLayout.setHorizontalGroup(
            interectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        interectPanelLayout.setVerticalGroup(
            interectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(interectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "Alamat", "Telepon", "Ayah Kandung", "Ibu Kandung", "Waktu", "User"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableSiswaMousePressed(evt);
            }
        });
        scrSiswa.setViewportView(tableSiswa);

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrSiswa)
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addComponent(scrSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(interectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(interectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        formInput.getAccessibleContext().setAccessibleParent(formInput);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (confirm("Data akan dihapus", "Hapus Data") == JOptionPane.NO_OPTION) return;
        
        dao.deleteSiswa(nisSiswa);
        loadData();
        removeInput();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void tableSiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMousePressed
        int SelectedRow = tableSiswa.rowAtPoint(evt.getPoint());
        
        if (SelectedRow != -1) {
            nisSiswa = (String) tableSiswa.getValueAt(SelectedRow, 0);
            tampilData(nisSiswa);
        }
    }//GEN-LAST:event_tableSiswaMousePressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if ("".equals(inputNis.getText())) {
            JOptionPane.showMessageDialog(this, "Anda belum menginput NIS");
            return;
        }
        String nis = inputNis.getText();
        
        Siswa siswa = dao.getSiswaByNis(nis);
        tableSiswa.setModel(dao.getModelSiswaBySiswa(siswa));
        scrSiswa.setViewportView(tableSiswa);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (confirm("Input akan dihapus", "Hapus Input") == JOptionPane.NO_OPTION) return;
        
        removeInput();
        loadData();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
        if (checkFill() == false) {
            JOptionPane.showMessageDialog(this, "Anda belum menginput semuanya");
            return;
        }

        if (confirm("Data akan disimpan", "Simpan Data") == JOptionPane.NO_OPTION) return;
        
        String nis = inputNis.getText().trim();
        String nama = inputNama.getText().trim();
        String tmpLahir = inputTmpLahir.getText().trim();
        Date tglLahir = new Date(inputTglLahir.getDate().getTime());
        String alamat = inputAlamat.getText().trim();
        String telp = inputTelepon.getText().trim();
        String ayah = inputAyah.getText().trim();
        String ibu = inputIbu.getText().trim();
        String user = inputUser.getText().trim();
        String foto = namaFile;
        String jenkel;
        jenkel = (inputRBLaki.isSelected()) ? "L" : (inputRBPerempuan.isSelected()) ? "P" : "";
        
        siswa = new Siswa(nis, nama, tmpLahir, tglLahir, alamat, jenkel, telp, ayah, ibu, user, foto);

        dao.saveSiswa(siswa);

        removeInput();
        loadData();
    }//GEN-LAST:event_btnSaveMousePressed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(
            System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.jpeg", ".jpg", ".png");
        file.addChoosableFileFilter(filter);
        int res = file.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File selFile = file.getSelectedFile();
            namaFile = selFile.getAbsolutePath();
            System.out.println(namaFile);
            if (namaFile == null || "".equals(namaFile)) {
                namaFile = null;
            } else {
                tampilGambar(namaFile);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {    
            public void run() {
                SiswaView s = new SiswaView();
//                s.loadData();
                s.setVisible(true);
            }
        });
    }
    
    public void loadData() {
        tableSiswa.setModel(dao.getModelAllSiswa());
        scrSiswa.setViewportView(tableSiswa);
    }
    
    public void tampilData(String nis) {
        Siswa siswa = dao.getSiswaByNis(nis);
        inputNis.setText(siswa.getNis());
        inputNama.setText(siswa.getNama());
        inputTmpLahir.setText(siswa.getTmpLahir());
        inputTglLahir.setDate(siswa.getTglLahir());
        inputAlamat.setText(siswa.getAlamat());
        inputTelepon.setText(siswa.getTelp());
        inputAyah.setText(siswa.getAyahKandung());
        inputIbu.setText(siswa.getIbuKandung());
        inputUser.setText(siswa.getUser());
        tampilGambar(siswa.getFoto());
        
        if ("L".equals(siswa.getJenkel())) inputRBLaki.setSelected(true);
        else if ("P".equals(siswa.getJenkel())) inputRBPerempuan.setSelected(true);
    }
    
    public void tampilGambar(String file) {
        try {
            BufferedImage myImage = ImageIO.read(new File(file));
            Image dimg = myImage.getScaledInstance(inputFoto.getWidth(), inputFoto.getHeight(), Image.SCALE_SMOOTH);
            inputFoto.setIcon(new ImageIcon(dimg));
        } catch (IOException | NullPointerException e) {
            namaFile = "";
            inputFoto.setIcon(null);
        }
    }
    
    public void removeInput() {
        for (JTextField textField : textFields) {
            textField.setText("");
        }
        inputAlamat.setText("");
        inputTglLahir.setDate(null);
        inputRBLaki.setSelected(false);
        inputRBPerempuan.setSelected(false);
        
        groupJenkel.clearSelection();        
        
        nisSiswa = "";
        
        inputFoto.setIcon(null);
    }
    
    public boolean checkFill() {
        for (JTextField textField : textFields) {
            if (textField.getText().isEmpty())
            return false;
        }
        if (inputAlamat.getText().isEmpty())
            return false;
        if (inputFoto.getIcon().equals(""))
            return false;
        if (inputRBLaki.isSelected() || inputRBPerempuan.isSelected())
            return true;
        
        return true;
    }
    
    public int confirm(String text, String title) {
        return JOptionPane.showOptionDialog(null, text, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel ayah;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpload;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel formInput;
    private javax.swing.JLabel foto;
    private javax.swing.ButtonGroup groupJenkel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel ibu;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputAyah;
    private javax.swing.JLabel inputFoto;
    private javax.swing.JTextField inputIbu;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNis;
    private javax.swing.JRadioButton inputRBLaki;
    private javax.swing.JRadioButton inputRBPerempuan;
    private javax.swing.JTextField inputTelepon;
    private com.toedter.calendar.JDateChooser inputTglLahir;
    private javax.swing.JTextField inputTmpLahir;
    private javax.swing.JTextField inputUser;
    private javax.swing.JPanel interectPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jenkel;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nis;
    private javax.swing.JScrollPane scrSiswa;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JLabel telepon;
    private javax.swing.JLabel tgllahir;
    private javax.swing.JLabel tmplahir;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
